name: object-detection-yolox
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools>=69
  - wheel
  - pytest
  - pytorch=2.10
  - torchvision=0.25
  - numpy
  - pandas
  - pillow
  - matplotlib
  - pycocotools
  - pyyaml
  - tqdm
  - ipykernel
  - ipywidgets
  - loguru
  - psutil
  - tabulate
  - tensorboard
  - pip:
      - opencv-python
      - thop
      - ninja
      - onnx
      - onnxsim
