name: objctrl
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools>=69
  - wheel
  - pytest
  - jupyterlab
  - notebook
  - ipykernel
  - jupytext
  - ipywidgets
  - nbconvert
  - numpy>=2.2,<2.4
  - pandas>=2.3,<3
  - matplotlib
  - scipy
  - scikit-learn
  - pillow
  - pyyaml
  - tqdm
  - ffmpeg
  - psutil
  - requests
  - polars
  - pycocotools
  - python-dotenv
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - torch==2.14.0+cu130
      - torchvision==0.29.0+cu130
      - ultralytics-opencv-headless==8.4.138
      - ultralytics-thop
      - loguru
      - thop
      - ninja
      - tabulate
      - tensorboard
      - onnx
      - onnx-simplifier==0.5.0
      - opencv-python-headless>=4.10,<5
      - supervision==0.30.2
      - roboflow==1.4.2
      - datumaro==1.13.11
